#!/usr/bin/env bash
# Vendor the root office-core source into each plugin as a pinned, committed snapshot.
#
# An installed plugin has to be complete on its own, so every plugin carries its own
# copy of the core it was built against. Run this after any edit under office-core/,
# then commit the refreshed snapshots.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/office-core"
PLUGINS=(codex-office claude-office agy-office auto-office)

[ -d "$SRC" ] || { echo "FAIL: no office-core source at $SRC" >&2; exit 1; }
VERSION="$(tr -d '[:space:]' < "$SRC/VERSION")"

# Content hash over the tracked core files, path-sensitive and order-stable.
core_hash() {
  local dir="$1"
  ( cd "$dir" && find . -type f ! -name SNAPSHOT.json -print0 \
      | LC_ALL=C sort -z \
      | xargs -0 shasum -a 256 \
      | shasum -a 256 | cut -d' ' -f1 )
}

HASH="$(core_hash "$SRC")"

for p in "${PLUGINS[@]}"; do
  dest="$ROOT/$p/office-core"
  rm -rf "$dest"
  mkdir -p "$dest"
  cp -R "$SRC/." "$dest/"
  rm -f "$dest/SNAPSHOT.json"
  cat > "$dest/SNAPSHOT.json" <<JSON
{
  "core_version": "$VERSION",
  "content_hash": "$HASH",
  "vendored_into": "$p",
  "source": "office-skills/office-core",
  "note": "Generated by scripts/vendor-core.sh. Never edit this snapshot by hand: edit the root office-core source, bump VERSION per protocol/compatibility.md, and re-vendor."
}
JSON
  echo "vendored core $VERSION -> $p/office-core"
done

echo "core_version=$VERSION content_hash=$HASH"
